### ISSUE TITLE
LinkTimeout randomly ignored

### ISSUE THREAD

**Issue by desbma** [tokio-rs/io-uring#156]
I have noticed in my program, that when adding a `LinkTimeout` operation after a `Connect`, sometimes (randomly) the timeout is ignored and the connect operation blocks forever.

**It seems to occur more frequently when the binary is compiled in release mode.**

I have made a minimal program, which allows me to reproduce 100% of the time (run with `cargo run --release`), the program should not block more that 3 seconds, but it does:

`Cargo.toml`:
```toml
[package]
name = "io_uring_test"
version = "0.1.0"
edition = "2021"

[dependencies]
io-uring = "0.5.9"
nix = { version = "0.25.0", default-features = false, features = ["net", "socket"] }
```

`src/main.rs`:
```rust
use io_uring::{
    opcode, squeue,
    types::{Fd, Timespec},
    IoUring,
};
use nix::sys::socket::{socket, AddressFamily, SockFlag, SockType, SockaddrIn, SockaddrLike};

fn main() {
    let mut ring = IoUring::new(8).unwrap();

    let sckt = socket(
        AddressFamily::Inet,
        SockType::Stream,
        SockFlag::empty(),
        None,
    )
    .unwrap();
    let addr = SockaddrIn::new(37, 187, 0, 1, 80);  // an IP that does not respond

    let op_connect = opcode::Connect::new(Fd(sckt), addr.as_ptr(), addr.len())
        .build()
        .flags(squeue::Flags::IO_LINK)
        .user_data(1);

    let op_connect_timeout = opcode::LinkTimeout::new(&Timespec::new().sec(3))
        .build()
        .user_data(2);

    let ops = [op_connect, op_connect_timeout];

    eprintln!("{ops:?}");

    for op in &ops {
        unsafe {
            ring.submission().push(op).unwrap();
        }
    }

    ring.submit_and_wait(2).unwrap();
}

```

EDIT: removed use of `unsafe` feature flag.
